language: android
env:
 global:
 - ANDROID_API=28
 - ANDROID_BUILD_TOOLS=28.0.3
before_install:
  cd Android;
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    # Test oldest supported version
    - sys-img-x86-android-14
    # Test oldest version with tun2socks and x86
    - sys-img-x86-android-23
    # Test newest supported version with Play Services and ARM
    - sys-img-armeabi-v7a-addon-google_apis-google-$GOOGLE_PLAY_SERVICES_API
script:
   - ./gradlew clean assembleDebug check
